import { Router } from "express";
import { requireAuth } from "../auth.js";

const router = Router();

router.use(requireAuth);

router.post("/send-document-email", async (req, res) => {
  const resendApiKey = process.env.RESEND_API_KEY;

  if (!resendApiKey || resendApiKey === "your-resend-api-key-here") {
    return res.status(500).json({
      error: "Email service not configured. Add your own RESEND_API_KEY in server/.env.",
    });
  }

  const { to, subject, documentType, content } = req.body || {};

  if (!to || !content) {
    return res.status(400).json({ error: "to and content are required" });
  }

  try {
    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${resendApiKey}`,
      },
      body: JSON.stringify({
        from: process.env.EMAIL_FROM || "LexiCloud <onboarding@resend.dev>",
        to: [to],
        subject: subject || `Legal Document: ${documentType || ""}`,
        html: `
          <h1>${subject || "Your Legal Document"}</h1>
          <p><strong>Document Type:</strong> ${documentType || "N/A"}</p>
          <hr/>
          <div style="white-space: pre-wrap; font-family: monospace;">${content}</div>
          <hr/>
          <p style="color: #666; font-size: 12px;">Generated by LexiCloud</p>
        `,
      }),
    });

    const data = await emailResponse.json();

    if (!emailResponse.ok) {
      throw new Error(data.message || "Failed to send email");
    }

    res.json(data);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
